# docker-compose.dev.yml
version: '3.8'

services:
  frontend:
    build: 
      context: ./angular
      dockerfile: Dockerfile.dev  # We'll create this
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  backend:
    build: 
      context: ./nestjs
      dockerfile: Dockerfile.dev  # We'll create this
    ports:
      - "3000:3000"
      - "9229:9229"  # For debugging
    volumes:
      - ./nestjs:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=dev
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=rentx_dev
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rentx_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge