version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - prod
    volumes:
      - pg_data:/var/lib/postgresql/data

  nestjs:
    container_name: back
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    env_file:
      - ./nestjs/.env.production
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "3000:3000"
    networks:
      - prod
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./default-test.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nestjs
    networks:
      - prod

networks:
  prod:
    driver: bridge

volumes:
  pg_data: